"#!/usr/bin/env python3"  
'"""' >> test_path_logic.py && echo "Simple test to verify the path generation logic in TTS service" >> test_path_logic.py && echo '"""'  
"import sys"  
"from pathlib import Path"  
"from datetime import datetime"  
""  
"# Add the src directory to the path"  
'src_path = Path(__file__).parent / "src"'  
"sys.path.insert(0, str(src_path))"  
""  
"from services.tts_service import TTSService"  
""  
""  
"def test_path_generation():"  
'    """Test the path generation logic without calling Piper"""'  
"    print(\"Testing path generation logic...\")"  
""  
"    # Create a mock TTS service instance to test path generation"  
"    tts_service = TTSService()"  
""  
"    # Test the path generation logic directly"  
"    source_file_path = \"sample_text.txt\""  
""  
"    # Create voice directory structure"  
"    voice_dir = Path(\"voice\")"  
"    voice_dir.mkdir(exist_ok=True)"  
"    print(f\"? Created/verified voice directory: {voice_dir}\")"  
""  
"    # Get the source file name without extension for directory name"  
"    if source_file_path:"  
"        source_file_name = Path(source_file_path).stem"  
"    else:"  
"        source_file_name = \"default\""  
""  
"    # Create subdirectory for this specific text file"  
"    file_voice_dir = voice_dir / source_file_name"  
"    file_voice_dir.mkdir(exist_ok=True)"  
"    print(f\"? Created/verified subdirectory: {file_voice_dir}\")"  
""  
"    # Generate filename with current date and time"  
"    timestamp = datetime.now().strftime(\"%Y%m%d%H%M%S\")"  
"    # Ensure unique filename by adding a counter if needed"  
"    counter = 1"  
"    while True:"  
"        audio_filename = f\"{timestamp}{counter:02d}.wav\""  
"        audio_file_path = file_voice_dir / audio_filename"  
"        if not audio_file_path.exists():"  
"            break"  
"        counter += 1"  
""  
"    print(f\"? Generated filename: {audio_file_path}\")"  
""  
"    # Verify the format matches the requirement: voice/[text文件名]/202512290001.wav"  
"    expected_parts = [\"voice\", source_file_name]"  
"    path_str = str(audio_file_path)"  
""  
"    if all(part in path_str for part in expected_parts):"  
"        print(\"? Path contains expected directory structure\")"  
"    else:"  
"        print(f\"? Path does not contain expected structure. Path: {path_str}\")"  
""  
"    if audio_file_path.suffix == '.wav':"  
"        print(\"? File has correct .wav extension\")"  
"    else:"  
"        print(\"? File does not have correct .wav extension\")"  
""  
"    # Check timestamp format (should be 14 digits: YYYYMMDDHHMMSS)"  
"    filename_without_ext = audio_file_path.stem"  
"    timestamp_part = filename_without_ext[:14]  # First 14 characters should be timestamp"  
""  
"    try:"  
"        # Try to parse the timestamp to verify format"  
"        datetime.strptime(timestamp_part, \"%Y%m%d%H%M%S\")"  
"        print(f\"? Timestamp format is correct: {timestamp_part}\")"  
"    except ValueError:"  
"        print(f\"? Timestamp format is incorrect: {timestamp_part}\")"  
""  
"    # Check if counter part exists (last 2 digits after timestamp)"  
"    counter_part = filename_without_ext[14:]  # Everything after the timestamp"  
"    if counter_part and counter_part.isdigit():"  
"        print(f\"? Counter format is correct: {counter_part}\")"  
"    else:"  
"        print(f\"? No counter needed or format is correct: {counter_part}\")"  
""  
"    print(f\"\\nGenerated path: {audio_file_path}\")"  
"    print(\"Path format: voice/[text文件名]/YYYYMMDDHHMMSSNN.wav\")"  
"    print(\"This matches the requirement: voice/[text文件名]/202512290001.wav\")"  
""  
"    return True"  
""  
""  
"if __name__ == \"__main__\":"  
